/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'imageDescription' : string,
  'publishedDate' : string,
  'timestamp' : bigint,
}
export interface Inquiry {
  'id' : bigint,
  'riceVariety' : string,
  'country' : string,
  'name' : string,
  'company' : string,
  'message' : string,
  'timestamp' : bigint,
  'quantityMT' : number,
}
export interface Service {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'details' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Attempt admin login. On success, assigns the #admin role to the caller's principal.
   * / The caller must not be anonymous (anonymous principals cannot hold roles).
   */
  'adminLogin' : ActorMethod<[string, string], boolean>,
  /**
   * / Revoke admin role from the caller (logout).
   */
  'adminLogout' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Clear all inquiries. Admin-only.
   */
  'clearInquiries' : ActorMethod<[], undefined>,
  /**
   * / Create a new blog post. Admin-only.
   */
  'createBlogPost' : ActorMethod<[string, string, string, string], bigint>,
  /**
   * / Create a new service listing. Admin-only.
   */
  'createService' : ActorMethod<[string, string, string], bigint>,
  /**
   * / Delete a blog post. Admin-only.
   */
  'deleteBlogPost' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete an individual inquiry by ID. Admin-only.
   */
  'deleteInquiry' : ActorMethod<[bigint], undefined>,
  /**
   * / Delete a service listing. Admin-only.
   */
  'deleteService' : ActorMethod<[bigint], undefined>,
  /**
   * / Edit an existing blog post. Admin-only.
   */
  'editBlogPost' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
  /**
   * / Edit an existing service listing. Admin-only.
   */
  'editService' : ActorMethod<[bigint, string, string, string], undefined>,
  /**
   * / Retrieve a single blog post by ID. Public.
   */
  'getBlogPost' : ActorMethod<[bigint], [] | [BlogPost]>,
  /**
   * / Retrieve all published blog posts. Public.
   */
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Retrieve all inquiries. Admin-only.
   */
  'getInquiries' : ActorMethod<[], Array<Inquiry>>,
  /**
   * / Retrieve a single service by ID. Public.
   */
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  /**
   * / Retrieve all services. Public.
   */
  'getServices' : ActorMethod<[], Array<Service>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Check whether the caller currently holds the admin role.
   */
  'isAdminLoggedIn' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit a new inquiry. Open to any caller (including guests).
   */
  'submitInquiry' : ActorMethod<
    [string, string, string, string, number, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];