/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const InquiryStatus = IDL.Variant({
  'resolved' : IDL.Null,
  'pending' : IDL.Null,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : InquiryStatus,
  'country' : IDL.Text,
  'riceCategory' : IDL.Text,
  'name' : IDL.Text,
  'submittedAt' : IDL.Int,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'quantityMT' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteInquiry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markResolved' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitInquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'validateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const InquiryStatus = IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : InquiryStatus,
    'country' : IDL.Text,
    'riceCategory' : IDL.Text,
    'name' : IDL.Text,
    'submittedAt' : IDL.Int,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'quantityMT' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteInquiry' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getInquiries' : IDL.Func([IDL.Text], [IDL.Vec(Inquiry)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markResolved' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitInquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'validateAdmin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(IDL.Text)], []),
  });
};

export const init = ({ IDL }) => { return []; };